# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kristinelin
# "service" is the name of this project. This will also be added to your AWS resource names.
service: cee6-sls-kristine
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  kristine:
    handler: handler.hello
    events:
      - httpApi:
          path: /kristine
          method: get
